# Basic dependabot.yml file with
# minimum configuration for nuget
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/keeping-your-dependencies-updated-automatically

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/samples/energinet/synchronous-ingestor/"
    schedule:
      interval: "weekly"
    ignore:
      # .NET 5 dependency: no Azure Functions support yet
      # https://github.com/Azure/azure-functions-host/issues/6674
      - dependency-name: "Microsoft.Extensions.DependencyInjection"
        versions: ["5.x"]

  - package-ecosystem: "nuget"
    directory: "/src/messaging/"
    schedule:
      interval: "weekly"
    ignore:
      # .NET 5 dependency: no Azure Functions support yet
      # https://github.com/Azure/azure-functions-host/issues/6674
      - dependency-name: "Microsoft.Extensions.DependencyInjection"
        versions: ["5.x"]

  - package-ecosystem: "nuget"
    directory: "/src/master-data/GreenEnergyHub.MasterData/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/src/master-data/GreenEnergyHub.Streaming/"
    schedule:
      interval: "weekly"